### ISSUE TITLE
get a domain name and switch to it

### ISSUE THREAD

**Issue by ln1draw** [ln1draw/nwnets#11]
Note: this costs money, which is a blocker!

Talk to @shubha-rajan about whether the redbubble store has raised enough to make the purchase.

maybe nwnets.com?

**Comment by shubha-rajan** [comment]
nwnets.com is already claimed by the Northwest Elite Talent Showcase. 
Both ethicaltechnw and nwethicaltech are available though,  in both the .com and .org flavors, and are within our budget.
