### ISSUE TITLE
license logo!

### ISSUE THREAD

**Issue by ln1draw** [ln1draw/nwnets#15]
license the logo!

Only @shubha-rajan can do this, as she created the art :)

license under creative commons, hippocratic license, whatever floats your boat?

**Comment by shubha-rajan** [comment]
Done! Gonna make a PR to link to this version in the 

https://commons.wikimedia.org/wiki/File:Pull_The_Plug_on_ICE.png

**Comment by shubha-rajan** [comment]
Done! 
https://commons.wikimedia.org/wiki/File:Pull_The_Plug_on_ICE.png
