### ISSUE TITLE
Add branding specification page

### ISSUE THREAD

**Issue by ln1draw** [ln1draw/nwnets#7]
We should include a page with the branding specifications for the logo and a link to download it, so other people can use it and spread it.

This includes:

- creating a link
- creating a route to a page
- creating a page
- making information about the color, font, etc of the logo available for the user
- making a download of the logo available for the user

**Comment by ln1draw** [comment]
Probably a high priority issue! bc branding is good/important to our cause. VISIBLE ANTI-FASCISM, YAY, LET'S SPREAD IT!

**Comment by ln1draw** [comment]
PR here! https://github.com/ln1draw/nwnets/pull/14

**Comment by Mildred14** [comment]
Hi @ln1draw  I would like to help you to solve this issue

**Comment by ln1draw** [comment]
Hi @Mildred14 , excited to see your enthusiasm! This issue was resolved with a PR that was accepted a couple of days before you added that comment, though. There are a lot of other issues in the repo you can take a look at though!
